"""add genres bands_genres

Revision ID: 288238caef70
Revises: 75cc57118666
Create Date: 2022-04-14 07:42:51.520402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288238caef70'
down_revision = '75cc57118666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_table('bands_genres',
    sa.Column('band_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['band_id'], ['bands.band_id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.genre_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bands_genres')
    op.drop_table('genres')
    # ### end Alembic commands ###
