"""empty message

Revision ID: 75cc57118666
Revises: e1a88bcac1ba
Create Date: 2022-04-11 10:55:00.051129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75cc57118666'
down_revision = 'e1a88bcac1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musics', sa.Column('duration', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('musics', 'duration')
    # ### end Alembic commands ###
