"""empty message

Revision ID: 72388f9e114b
Revises: 
Create Date: 2022-04-06 14:07:55.805564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72388f9e114b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salgados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salgados')
    # ### end Alembic commands ###
