"""adcionando tabela 'donos'

Revision ID: 0474af728e6b
Revises: 
Create Date: 2022-04-12 13:27:50.786797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0474af728e6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cachorros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('raca', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('idade', sa.String(), nullable=False),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('cachorro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cachorro_id'], ['cachorros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cachorro_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donos')
    op.drop_table('cachorros')
    # ### end Alembic commands ###
